# Generated by Django 3.0 on 2022-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='URL',
            new_name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
