# Generated by Django 3.2.16 on 2022-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20221024_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.ImageField(max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(max_length=128, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
