# Generated by Django 3.2.16 on 2022-10-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20221025_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album_ID',
            new_name='albumId',
        ),
    ]
